import json
import os
import subprocess

def extract_score(result):
    # 使用正则表达式提取JSON
    import re
    json_pattern = re.compile(r'{.*}', re.DOTALL)
    match = json_pattern.search(result)
    
    if match:
        try:
            submission_json_str = match.group(0)
            return submission_json_str
        except Exception as e:
            print(f"提取score时发生错误: {e}")
    return str(result)

def diff_submission_csv(origin_submission_file: str, submission_file: str):
    diff_res = subprocess.run(['diff', submission_file, origin_submission_file], capture_output=True, text=True).stdout

    if diff_res.strip():
        return True
    else:
        return False
def re_submit(result_path: str, task_id: str):
    cmd = f"mlebench grade-sample {result_path} {task_id}"
    submit_score = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    # print({
    #     'stderr': submit_score.stderr,
    #     'stdout': submit_score.stdout
    # })
    return extract_score(submit_score.stderr)

def load_submission(path: str):
    new_submission_path = path.replace('.json', '_new.json')
    new_submission = []
    with open(path, 'r') as f:
        for line in f.readlines():
            submission = json.loads(line)
            # import pdb; pdb.set_trace()
            score = submission['score']
            work_dir = submission['work_dir']
            task_id = os.path.basename(os.path.dirname(work_dir))
            origin_submission_csv = f'/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/{task_id}/prepared/public/sample_submission.csv'
            submission_csv = work_dir + '/data/sample_submission.csv'
            if '提交失败 | [Errno 2] No such file or directory' in score:
                if os.path.exists(submission_csv):
                    if diff_submission_csv(origin_submission_csv, submission_csv):
                        new_score = re_submit(submission_csv, task_id)
                        submission['score'] = new_score
                        new_submission.append(submission)
                        continue
            new_submission.append(submission)
    with open(new_submission_path, 'w') as f:
        for submission in new_submission:
            f.write(json.dumps(submission, ensure_ascii=False) + '\n')
    return new_submission_path

def get_task_completed():
    completed_task = [
        {"task_id": "aerial-cactus-identification", "score": "{\n    \"competition_id\": \"aerial-cactus-identification\",\n    \"score\": 0.99987,\n    \"gold_threshold\": 1.0,\n    \"silver_threshold\": 1.0,\n    \"bronze_threshold\": 1.0,\n    \"median_threshold\": 0.9991,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": true,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T07:27:02.902465\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task7/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task7/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/Aerial-Cactus-Identification", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/aerial-cactus-identification/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task7/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/sample_submission.csv aerial-cactus-identification"},
        {"task_id": "aerial-cactus-identification", "score": "{\n    \"competition_id\": \"aerial-cactus-identification\",\n    \"score\": 0.99321,\n    \"gold_threshold\": 1.0,\n    \"silver_threshold\": 1.0,\n    \"bronze_threshold\": 1.0,\n    \"median_threshold\": 0.9991,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T07:04:25.709372\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task75/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/aerial-cactus-identification/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task75/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/aerial-cactus-identification/Aerial-Cactus-Identification", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/aerial-cactus-identification/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task75/aerial-cactus-identification/DishinGoyani_Aerial-Cactus-Identification/aerial-cactus-identification/sample_submission.csv aerial-cactus-identification"},
        {"task_id": "histopathologic-cancer-detection", "score": "{\n    \"competition_id\": \"histopathologic-cancer-detection\",\n    \"score\": 0.97757,\n    \"gold_threshold\": 0.9835,\n    \"silver_threshold\": 0.9798,\n    \"bronze_threshold\": 0.9738,\n    \"median_threshold\": 0.9477,\n    \"any_medal\": true,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": true,\n    \"above_median\": true,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T13:24:30.571701\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/histopathologic-cancer-detection/mitch-henderson_MetastaticCancerDetection-PcamAnalysis/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/histopathologic-cancer-detection/mitch-henderson_MetastaticCancerDetection-PcamAnalysis/MetastaticCancerDetection-PcamAnalysis", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/histopathologic-cancer-detection/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/histopathologic-cancer-detection/mitch-henderson_MetastaticCancerDetection-PcamAnalysis/sample_submission.csv histopathologic-cancer-detection", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/histopathologic-cancer-detection/mitch-henderson_MetastaticCancerDetection-PcamAnalysis"},
        {"task_id": "learning-agency-lab-automated-essay-scoring-2", "score": "{\n    \"competition_id\": \"learning-agency-lab-automated-essay-scoring-2\",\n    \"score\": 0.69429,\n    \"gold_threshold\": 0.83583,\n    \"silver_threshold\": 0.83518,\n    \"bronze_threshold\": 0.83471,\n    \"median_threshold\": 0.828265,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T13:53:10.421605\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Jatin-Mehra119_Essay-Scoring-Modeling/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Jatin-Mehra119_Essay-Scoring-Modeling/Essay-Scoring-Modeling", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/learning-agency-lab-automated-essay-scoring-2/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Jatin-Mehra119_Essay-Scoring-Modeling/sample_submission.csv learning-agency-lab-automated-essay-scoring-2", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Jatin-Mehra119_Essay-Scoring-Modeling"},
        {"task_id": "learning-agency-lab-automated-essay-scoring-2", "score": "{\n    \"competition_id\": \"learning-agency-lab-automated-essay-scoring-2\",\n    \"score\": 0.78242,\n    \"gold_threshold\": 0.83583,\n    \"silver_threshold\": 0.83518,\n    \"bronze_threshold\": 0.83471,\n    \"median_threshold\": 0.828265,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-27T04:27:38.443258\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/stanfordjournalism_search-script-scrape/data/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/Tool-Learner/git_search/res/repositories/learning-agency-lab-automated-essay-scoring-2/stanfordjournalism/search-script-scrape", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/learning-agency-lab-automated-essay-scoring-2/prepared/public", "cmd": "", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/stanfordjournalism_search-script-scrape"},
        {"task_id": "learning-agency-lab-automated-essay-scoring-2", "score": "{\n    \"competition_id\": \"learning-agency-lab-automated-essay-scoring-2\",\n    \"score\": 0.72975,\n    \"gold_threshold\": 0.83583,\n    \"silver_threshold\": 0.83518,\n    \"bronze_threshold\": 0.83471,\n    \"median_threshold\": 0.828265,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T13:59:51.469975\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Lizhecheng02_Kaggle-Automated_Essay_Scoring_2.0/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Lizhecheng02_Kaggle-Automated_Essay_Scoring_2.0/Kaggle-Automated_Essay_Scoring_2.0", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/learning-agency-lab-automated-essay-scoring-2/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Lizhecheng02_Kaggle-Automated_Essay_Scoring_2.0/sample_submission.csv learning-agency-lab-automated-essay-scoring-2", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/learning-agency-lab-automated-essay-scoring-2/Lizhecheng02_Kaggle-Automated_Essay_Scoring_2.0"},
        {"task_id": "nomad2018-predict-transparent-conductors", "score": "{\n    \"competition_id\": \"nomad2018-predict-transparent-conductors\",\n    \"score\": 0.09727,\n    \"gold_threshold\": 0.05589,\n    \"silver_threshold\": 0.06229,\n    \"bronze_threshold\": 0.06582,\n    \"median_threshold\": 0.06988,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": true,\n    \"created_at\": \"2025-04-26T14:41:53.409490\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/nomad2018-predict-transparent-conductors/tvial_crystalz/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/nomad2018-predict-transparent-conductors/tvial_crystalz/crystalz", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/nomad2018-predict-transparent-conductors/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/nomad2018-predict-transparent-conductors/tvial_crystalz/sample_submission.csv nomad2018-predict-transparent-conductors", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/nomad2018-predict-transparent-conductors/tvial_crystalz"},
        {"task_id": "plant-pathology-2020-fgvc7", "score": "{\n    \"competition_id\": \"plant-pathology-2020-fgvc7\",\n    \"score\": 0.85344,\n    \"gold_threshold\": 0.97836,\n    \"silver_threshold\": 0.97465,\n    \"bronze_threshold\": 0.97361,\n    \"median_threshold\": 0.94852,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T14:47:12.228556\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/plant-pathology-2020-fgvc7/Kaggle_kaggle-api/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/plant-pathology-2020-fgvc7/Kaggle_kaggle-api/kaggle-api", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/plant-pathology-2020-fgvc7/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/plant-pathology-2020-fgvc7/Kaggle_kaggle-api/sample_submission.csv plant-pathology-2020-fgvc7", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/plant-pathology-2020-fgvc7/Kaggle_kaggle-api"},
        {"task_id": "jigsaw-toxic-comment-classification-challenge", "score": "{\n    \"competition_id\": \"jigsaw-toxic-comment-classification-challenge\",\n    \"score\": 0.98408,\n    \"gold_threshold\": 0.9874,\n    \"silver_threshold\": 0.98668,\n    \"bronze_threshold\": 0.98639,\n    \"median_threshold\": 0.98079,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": true,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T14:48:21.154431\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/jigsaw-toxic-comment-classification-challenge/balandhanka_TPU-Multilingual-Toxic-Comment-Classification/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/jigsaw-toxic-comment-classification-challenge/balandhanka_TPU-Multilingual-Toxic-Comment-Classification/TPU-Multilingual-Toxic-Comment-Classification", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/jigsaw-toxic-comment-classification-challenge/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/jigsaw-toxic-comment-classification-challenge/balandhanka_TPU-Multilingual-Toxic-Comment-Classification/sample_submission.csv jigsaw-toxic-comment-classification-challenge", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/jigsaw-toxic-comment-classification-challenge/balandhanka_TPU-Multilingual-Toxic-Comment-Classification"},
        {"task_id": "spooky-author-identification", "score": "{\n    \"competition_id\": \"spooky-author-identification\",\n    \"score\": 1.08555,\n    \"gold_threshold\": 0.16506,\n    \"silver_threshold\": 0.26996,\n    \"bronze_threshold\": 0.29381,\n    \"median_threshold\": 0.418785,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": true,\n    \"created_at\": \"2025-04-26T15:08:47.098143\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/spooky-author-identification/clairempr_spooky-classify/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/spooky-author-identification/clairempr_spooky-classify/spooky-classify", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/spooky-author-identification/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/spooky-author-identification/clairempr_spooky-classify/sample_submission.csv spooky-author-identification", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/spooky-author-identification/clairempr_spooky-classify"},
        {"task_id": "tabular-playground-series-dec-2021", "score": "{\n    \"competition_id\": \"tabular-playground-series-dec-2021\",\n    \"score\": 0.95259,\n    \"gold_threshold\": 0.9566,\n    \"silver_threshold\": 0.95658,\n    \"bronze_threshold\": 0.95658,\n    \"median_threshold\": 0.95342,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T15:22:03.098498\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/uxlfoundation_scikit-learn-intelex/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/uxlfoundation_scikit-learn-intelex/scikit-learn-intelex", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tabular-playground-series-dec-2021/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/uxlfoundation_scikit-learn-intelex/sample_submission.csv tabular-playground-series-dec-2021", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/uxlfoundation_scikit-learn-intelex"},
        {"task_id": "tabular-playground-series-dec-2021", "score": "{\n    \"competition_id\": \"tabular-playground-series-dec-2021\",\n    \"score\": 0.01973,\n    \"gold_threshold\": 0.9566,\n    \"silver_threshold\": 0.95658,\n    \"bronze_threshold\": 0.95658,\n    \"median_threshold\": 0.95342,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-27T04:27:41.960304\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/autogluon_autogluon/data/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/Tool-Learner/git_search/res/repositories/tabular-playground-series-dec-2021/autogluon/autogluon", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tabular-playground-series-dec-2021/prepared/public", "cmd": "", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-dec-2021/autogluon_autogluon"},
        {"task_id": "tabular-playground-series-may-2022", "score": "{\n    \"competition_id\": \"tabular-playground-series-may-2022\",\n    \"score\": 0.5247,\n    \"gold_threshold\": 0.99823,\n    \"silver_threshold\": 0.99822,\n    \"bronze_threshold\": 0.99818,\n    \"median_threshold\": 0.972675,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T15:54:50.202686\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/4paradigm_AutoX/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/4paradigm_AutoX/AutoX", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tabular-playground-series-may-2022/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/4paradigm_AutoX/sample_submission.csv tabular-playground-series-may-2022", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/4paradigm_AutoX"},
        {"task_id": "tabular-playground-series-may-2022", "score": "{\n    \"competition_id\": \"tabular-playground-series-may-2022\",\n    \"score\": 0.8006,\n    \"gold_threshold\": 0.99823,\n    \"silver_threshold\": 0.99822,\n    \"bronze_threshold\": 0.99818,\n    \"median_threshold\": 0.972675,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T15:58:13.930357\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/bchryzal_TPS-May-2022/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/bchryzal_TPS-May-2022/TPS-May-2022", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tabular-playground-series-may-2022/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/bchryzal_TPS-May-2022/sample_submission.csv tabular-playground-series-may-2022", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/bchryzal_TPS-May-2022"},
        {"task_id": "tabular-playground-series-may-2022", "score": "{\n    \"competition_id\": \"tabular-playground-series-may-2022\",\n    \"score\": 0.92751,\n    \"gold_threshold\": 0.99823,\n    \"silver_threshold\": 0.99822,\n    \"bronze_threshold\": 0.99818,\n    \"median_threshold\": 0.972675,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T16:03:05.240096\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/csotaku0926_Intro_to_ML_final_project/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/csotaku0926_Intro_to_ML_final_project/Intro_to_ML_final_project", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tabular-playground-series-may-2022/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/csotaku0926_Intro_to_ML_final_project/sample_submission.csv tabular-playground-series-may-2022", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tabular-playground-series-may-2022/csotaku0926_Intro_to_ML_final_project"},
        {"task_id": "new-york-city-taxi-fare-prediction", "score": "{\n    \"competition_id\": \"new-york-city-taxi-fare-prediction\",\n    \"score\": 5.06243,\n    \"gold_threshold\": 2.83377,\n    \"silver_threshold\": 2.88191,\n    \"bronze_threshold\": 2.92371,\n    \"median_threshold\": 3.59741,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": true,\n    \"created_at\": \"2025-04-26T17:32:20.254047\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/new-york-city-taxi-fare-prediction/errhythm_NYCTaxiFarePred-Extended/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/new-york-city-taxi-fare-prediction/errhythm_NYCTaxiFarePred-Extended/NYCTaxiFarePred-Extended", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/new-york-city-taxi-fare-prediction/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/new-york-city-taxi-fare-prediction/errhythm_NYCTaxiFarePred-Extended/sample_submission.csv new-york-city-taxi-fare-prediction", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/new-york-city-taxi-fare-prediction/errhythm_NYCTaxiFarePred-Extended"},
        {"task_id": "tgs-salt-identification-challenge", "score": "{\n    \"competition_id\": \"tgs-salt-identification-challenge\",\n    \"score\": 0.5221,\n    \"gold_threshold\": 0.89097,\n    \"silver_threshold\": 0.87163,\n    \"bronze_threshold\": 0.85918,\n    \"median_threshold\": 0.81665,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T19:30:10.961249\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tgs-salt-identification-challenge/matin-ghorbani_Salt-Segmentation-UNet/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tgs-salt-identification-challenge/matin-ghorbani_Salt-Segmentation-UNet/Salt-Segmentation-UNet", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/tgs-salt-identification-challenge/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tgs-salt-identification-challenge/matin-ghorbani_Salt-Segmentation-UNet/sample_submission.csv tgs-salt-identification-challenge", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/tgs-salt-identification-challenge/matin-ghorbani_Salt-Segmentation-UNet"},
        {"task_id": "ranzcr-clip-catheter-line-classification", "score": "{\n    \"competition_id\": \"ranzcr-clip-catheter-line-classification\",\n    \"score\": 0.84915,\n    \"gold_threshold\": 0.97357,\n    \"silver_threshold\": 0.97152,\n    \"bronze_threshold\": 0.9709,\n    \"median_threshold\": 0.9675,\n    \"any_medal\": false,\n    \"gold_medal\": false,\n    \"silver_medal\": false,\n    \"bronze_medal\": false,\n    \"above_median\": false,\n    \"submission_exists\": true,\n    \"valid_submission\": true,\n    \"is_lower_better\": false,\n    \"created_at\": \"2025-04-26T21:55:03.448342\",\n    \"submission_path\": \"/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/ranzcr-clip-catheter-line-classification/raufbhat-dev_archives/sample_submission.csv\"\n}", "repo_path": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/ranzcr-clip-catheter-line-classification/raufbhat-dev_archives/archives", "data_path": "/mnt/ceph/huacan/Code/Tasks/CodeAgent/data/mle-bench-data/data/ranzcr-clip-catheter-line-classification/prepared/public", "cmd": "mlebench grade-sample /mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/ranzcr-clip-catheter-line-classification/raufbhat-dev_archives/sample_submission.csv ranzcr-clip-catheter-line-classification", "work_dir": "/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/coding/task23/ranzcr-clip-catheter-line-classification/raufbhat-dev_archives"},
        
    ]
    return completed_task

if __name__ == "__main__":
    # submission = load_submission("/mnt/ceph/huacan/Code/Tasks/Code-Repo-Agent/res/submission/submission_20250426_123838.json")
    
    get_task_completed()

